{{- if .Values.admin.create }}
apiVersion: storage.loft.sh/v1
kind: User
metadata:
  name: {{ include "loft.admin.name" . }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  username: {{ .Values.admin.username }}
  {{- if .Values.admin.email }}
  email: {{ .Values.admin.email }}
  {{- end }}
  groups: ["loft:admins"]
  subject: admin
  description: The Loft admin user that is allowed to do anything in all connected clusters
  {{- if ne .Values.admin.password "" }}
  passwordRef:
    secretName: loft-user-secret-admin
    secretNamespace: {{ .Release.Namespace }}
    key: password
  {{- end }}
---
{{- if .Values.admin.password }}
apiVersion: v1
kind: Secret
metadata:
  name: loft-user-secret-admin
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
data:
  password: {{ .Values.admin.password | sha256sum | b64enc }}
{{- end }}
{{- end }}
